// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZgDW1GxkX715JTcvBKG_wOqr8GM1zqs',
    appId: '1:223012357996:web:a5f0413369d0ec28bf1549',
    messagingSenderId: '223012357996',
    projectId: 'instagram-app-427b8',
    authDomain: 'instagram-app-427b8.firebaseapp.com',
    storageBucket: 'instagram-app-427b8.appspot.com',
    measurementId: 'G-NP1KKJP15Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmstfDZ9jP8-gfjpF34F_GtnApN-b1RMs',
    appId: '1:223012357996:android:7f70f04792b95497bf1549',
    messagingSenderId: '223012357996',
    projectId: 'instagram-app-427b8',
    storageBucket: 'instagram-app-427b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItlqiDVswGyESHf5SPXtpRr0IY6oKfI0',
    appId: '1:223012357996:ios:9c6ad9d479364899bf1549',
    messagingSenderId: '223012357996',
    projectId: 'instagram-app-427b8',
    storageBucket: 'instagram-app-427b8.appspot.com',
    androidClientId: '223012357996-4dd5u2trh2v5ggb46oq1pseb0lchcpqv.apps.googleusercontent.com',
    iosClientId: '223012357996-2v51cvr9i41cs0oi58d85t91u1cvf7f4.apps.googleusercontent.com',
    iosBundleId: 'safwat.tec.instantgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBItlqiDVswGyESHf5SPXtpRr0IY6oKfI0',
    appId: '1:223012357996:ios:9c6ad9d479364899bf1549',
    messagingSenderId: '223012357996',
    projectId: 'instagram-app-427b8',
    storageBucket: 'instagram-app-427b8.appspot.com',
    androidClientId: '223012357996-4dd5u2trh2v5ggb46oq1pseb0lchcpqv.apps.googleusercontent.com',
    iosClientId: '223012357996-2v51cvr9i41cs0oi58d85t91u1cvf7f4.apps.googleusercontent.com',
    iosBundleId: 'safwat.tec.instantgram',
  );
}
